// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzkfpehizmdanujfbcsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6a2ZwZWhpem1kYW51amZiY3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTQyOTMsImV4cCI6MjA2NjMzMDI5M30._2Rw_Ypi-zEWAHjL3H6LtZQT6hLIVCwsEZsarbOj-Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);